name: SSE Brocker Container CI

on:
  push:
    branches:
    - master
    tags:
    - "**"

permissions:
  packages: write
  contents: write

jobs:
  test:
    name: go_test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Install dependencies
        run: go mod download && go mod verify
      - name: Run tests
        run: go test -v ./...

  build_container:
    name: build container
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set build env
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push core
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/sse-broker:latest
            ghcr.io/${{ env.GHCR_OWNER }}/sse-broker:${{ github.ref_name }}
